/**
 * Hand-authored yoga and pilates entries.
 *
 * No open dataset carries reliable muscle data for these, so they are written
 * out by hand against standard references: Yoga Journal cues for the asanas and
 * classical BASI/Stott mat cues for the pilates work.
 *
 * These are NOT seeded by import_exercises.js — the script only renders them to
 * yoga_pilates_review.md for a human to check first.
 */

const YOGA_PILATES_ENTRIES = [
  // ── Yoga ────────────────────────────────────────────────────────────────
  {
    name: 'Downward-Facing Dog',
    category: 'Yoga',
    subcategory: 'Standing',
    equipment_type: 'mat',
    muscles_primary: ['upper-back', 'hamstring', 'front-deltoids'],
    muscles_secondary: ['calves', 'triceps', 'gluteal', 'abs'],
    description: 'Adho Mukha Svanasana. Foundational inversion that lengthens the whole posterior chain while building shoulder stability.',
    instructions: [
      'Start on hands and knees, wrists under shoulders and knees under hips.',
      'Spread the fingers wide and press evenly through the whole hand.',
      'Tuck the toes and lift the hips up and back toward the ceiling.',
      'Straighten the legs as far as the hamstrings allow, keeping a long spine.',
      'Draw the shoulder blades down the back and let the head hang between the arms.',
      'Hold for 5 to 10 breaths.',
    ],
  },
  {
    name: 'Warrior I',
    category: 'Yoga',
    subcategory: 'Standing',
    equipment_type: 'mat',
    muscles_primary: ['quadriceps', 'gluteal'],
    muscles_secondary: ['front-deltoids', 'calves', 'abs', 'adductor'],
    description: 'Virabhadrasana I. Standing lunge that opens the hip flexors and chest while loading the front leg.',
    instructions: [
      'From standing, step the left foot back about four feet and turn it out 45 degrees.',
      'Square the hips toward the front of the mat.',
      'Bend the right knee until it stacks over the right ankle.',
      'Press the outer edge of the back foot down and straighten the back leg.',
      'Reach both arms overhead, palms facing each other.',
      'Hold for 5 breaths, then repeat on the other side.',
    ],
  },
  {
    name: 'Warrior II',
    category: 'Yoga',
    subcategory: 'Standing',
    equipment_type: 'mat',
    muscles_primary: ['quadriceps', 'gluteal', 'adductor'],
    muscles_secondary: ['front-deltoids', 'abs', 'calves'],
    description: 'Virabhadrasana II. Open-hipped standing pose that builds isometric strength in the legs and shoulders.',
    instructions: [
      'Step the feet wide apart and turn the right foot out 90 degrees.',
      'Align the right heel with the arch of the left foot.',
      'Open the hips and chest to the long edge of the mat.',
      'Bend the right knee over the right ankle, keeping the shin vertical.',
      'Extend the arms parallel to the floor and gaze past the front fingertips.',
      'Hold for 5 breaths, then repeat on the other side.',
    ],
  },
  {
    name: "Child's Pose",
    category: 'Yoga',
    subcategory: 'Restorative',
    equipment_type: 'mat',
    muscles_primary: ['lower-back'],
    muscles_secondary: ['upper-back', 'quadriceps'],
    description: "Balasana. Resting pose that decompresses the lower back and gently stretches the hips and ankles.",
    instructions: [
      'Kneel on the mat with the big toes touching and knees apart.',
      'Sit the hips back toward the heels.',
      'Walk the hands forward and lower the forehead to the mat.',
      'Let the arms rest extended or alongside the body.',
      'Breathe into the back of the ribcage for 5 to 10 breaths.',
    ],
  },
  {
    name: 'Cat-Cow',
    category: 'Yoga',
    subcategory: 'Mobility',
    equipment_type: 'mat',
    muscles_primary: ['lower-back', 'abs'],
    muscles_secondary: ['upper-back', 'trapezius'],
    description: 'Marjaryasana-Bitilasana. Paired spinal flexion and extension that warms the whole back.',
    instructions: [
      'Start on hands and knees with a neutral spine.',
      'Inhale, drop the belly, lift the chest and tailbone for cow.',
      'Exhale, round the spine, tuck the tailbone and chin for cat.',
      'Move with the breath, one position per breath.',
      'Repeat for 8 to 10 cycles.',
    ],
  },
  {
    name: 'Cobra Pose',
    category: 'Yoga',
    subcategory: 'Backbend',
    equipment_type: 'mat',
    muscles_primary: ['lower-back', 'upper-back'],
    muscles_secondary: ['triceps', 'gluteal', 'chest'],
    description: 'Bhujangasana. Prone backbend that strengthens the spinal extensors and opens the front of the chest.',
    instructions: [
      'Lie face down with the tops of the feet on the mat.',
      'Place the hands under the shoulders, elbows hugged in.',
      'Press the pubic bone down and draw the shoulders back.',
      'Lift the chest using the back muscles, keeping weight light in the hands.',
      'Keep the neck long and the gaze forward.',
      'Hold for 3 to 5 breaths, then lower.',
    ],
  },
  {
    name: 'Tree Pose',
    category: 'Yoga',
    subcategory: 'Balance',
    equipment_type: 'mat',
    muscles_primary: ['gluteal', 'quadriceps'],
    muscles_secondary: ['calves', 'abs', 'obliques', 'adductor'],
    description: 'Vrksasana. Single-leg balance that trains ankle stability and hip abductor control.',
    instructions: [
      'Stand tall and shift weight into the left foot.',
      'Place the right sole on the left calf or inner thigh, never on the knee.',
      'Press the foot and leg into each other to stabilise.',
      'Bring the hands to the heart or reach them overhead.',
      'Fix the gaze on a still point and hold for 5 to 8 breaths.',
      'Repeat on the other side.',
    ],
  },
  {
    name: 'Mountain Pose',
    category: 'Yoga',
    subcategory: 'Standing',
    equipment_type: 'mat',
    muscles_primary: ['quadriceps', 'abs'],
    muscles_secondary: ['calves', 'gluteal', 'upper-back'],
    description: 'Tadasana. Standing foundation pose that establishes alignment for every other standing posture.',
    instructions: [
      'Stand with the feet hip-width apart, weight even across both feet.',
      'Engage the quadriceps and lengthen the tailbone down.',
      'Stack the ribs over the pelvis and draw the low ribs in.',
      'Roll the shoulders back and down, arms alongside the body.',
      'Breathe evenly for 5 to 10 breaths.',
    ],
  },
  {
    name: 'Bridge Pose',
    category: 'Yoga',
    subcategory: 'Backbend',
    equipment_type: 'mat',
    muscles_primary: ['gluteal', 'hamstring'],
    muscles_secondary: ['lower-back', 'abs', 'quadriceps'],
    description: 'Setu Bandha Sarvangasana. Supine backbend that strengthens the posterior chain and opens the hip flexors.',
    instructions: [
      'Lie on the back with knees bent and feet hip-width apart.',
      'Bring the heels close enough to graze the fingertips.',
      'Press through the feet and lift the hips toward the ceiling.',
      'Roll the shoulders under and clasp the hands beneath the back if comfortable.',
      'Keep the knees tracking over the ankles.',
      'Hold for 5 breaths, then lower one vertebra at a time.',
    ],
  },
  {
    name: 'Pigeon Pose',
    category: 'Yoga',
    subcategory: 'Hip Opener',
    equipment_type: 'mat',
    muscles_primary: ['gluteal'],
    muscles_secondary: ['adductor', 'lower-back', 'quadriceps'],
    description: 'Eka Pada Rajakapotasana (prep). Deep external hip rotation stretch for the glutes and outer hip.',
    instructions: [
      'From downward dog, bring the right knee forward behind the right wrist.',
      'Angle the right shin toward the left wrist as the hip allows.',
      'Extend the left leg straight back with the kneecap facing the floor.',
      'Square the hips and support with a block or blanket if they tilt.',
      'Walk the hands forward and fold over the front shin.',
      'Hold for 8 to 10 breaths, then switch sides.',
    ],
  },

  // ── Pilates ─────────────────────────────────────────────────────────────
  {
    name: 'The Hundred',
    category: 'Pilates',
    subcategory: 'Mat',
    equipment_type: 'mat',
    muscles_primary: ['abs'],
    muscles_secondary: ['obliques', 'front-deltoids', 'quadriceps'],
    description: 'Classical mat warm-up that builds abdominal endurance and coordinates breath with pumping arms.',
    instructions: [
      'Lie supine, draw the knees into tabletop.',
      'Curl the head, neck and shoulders off the mat into a chest lift.',
      'Extend the legs to a height the low back can hold flat.',
      'Reach the arms long by the hips and pump them briskly up and down.',
      'Inhale for five pumps, exhale for five pumps.',
      'Continue for 10 full breath cycles, 100 pumps total.',
    ],
  },
  {
    name: 'Roll-Up',
    category: 'Pilates',
    subcategory: 'Mat',
    equipment_type: 'mat',
    muscles_primary: ['abs'],
    muscles_secondary: ['obliques', 'hamstring', 'lower-back'],
    description: 'Slow sequential spinal articulation that strengthens the deep abdominals through full flexion.',
    instructions: [
      'Lie supine with the legs straight and arms reaching overhead.',
      'Inhale and float the arms to the ceiling.',
      'Exhale, tuck the chin and peel the spine off the mat one vertebra at a time.',
      'Reach over the legs at the top, keeping the abdominals hollow.',
      'Inhale, then exhale to roll back down with the same control.',
      'Repeat 5 to 8 times.',
    ],
  },
  {
    name: 'Single Leg Circle',
    category: 'Pilates',
    subcategory: 'Mat',
    equipment_type: 'mat',
    muscles_primary: ['abs', 'quadriceps'],
    muscles_secondary: ['adductor', 'gluteal', 'obliques'],
    description: 'Hip disassociation drill that trains the abdominals to stabilise the pelvis while the leg moves.',
    instructions: [
      'Lie supine with one leg extended along the mat and the other to the ceiling.',
      'Anchor both hips and the ribcage into the mat.',
      'Draw a controlled circle with the raised leg, crossing the midline first.',
      'Keep the pelvis completely still throughout.',
      'Complete 5 circles in each direction, then switch legs.',
    ],
  },
  {
    name: 'Double Leg Stretch',
    category: 'Pilates',
    subcategory: 'Mat',
    equipment_type: 'mat',
    muscles_primary: ['abs'],
    muscles_secondary: ['obliques', 'front-deltoids', 'quadriceps'],
    description: 'Dynamic abdominal exercise coordinating simultaneous arm and leg extension against a stable trunk.',
    instructions: [
      'Begin in a chest lift with the knees in tabletop and hands on the shins.',
      'Inhale and extend the arms overhead as the legs reach long on a diagonal.',
      'Keep the low back imprinted into the mat.',
      'Exhale, circle the arms around and draw the knees back in.',
      'Repeat 6 to 10 times.',
    ],
  },
  {
    name: 'Spine Stretch Forward',
    category: 'Pilates',
    subcategory: 'Mat',
    equipment_type: 'mat',
    muscles_primary: ['abs', 'lower-back'],
    muscles_secondary: ['hamstring', 'upper-back'],
    description: 'Seated forward articulation that lengthens the spine and hamstrings while engaging the deep abdominals.',
    instructions: [
      'Sit tall with the legs extended slightly wider than the mat, feet flexed.',
      'Reach the arms forward at shoulder height.',
      'Inhale to grow taller through the crown of the head.',
      'Exhale, tuck the chin and roll forward one vertebra at a time.',
      'Inhale at the bottom, then exhale to restack the spine.',
      'Repeat 4 to 6 times.',
    ],
  },
  {
    name: 'Swan',
    category: 'Pilates',
    subcategory: 'Mat',
    equipment_type: 'mat',
    muscles_primary: ['lower-back', 'upper-back'],
    muscles_secondary: ['gluteal', 'triceps', 'chest'],
    description: 'Prone extension that balances the flexion-heavy mat repertoire and strengthens the spinal extensors.',
    instructions: [
      'Lie prone with the hands under the shoulders and legs hip-width apart.',
      'Draw the abdominals up and lengthen the tailbone toward the heels.',
      'Inhale and press the chest forward and up into extension.',
      'Keep the shoulders drawing away from the ears.',
      'Exhale to lower with control.',
      'Repeat 5 to 8 times.',
    ],
  },
  {
    name: 'Side Leg Series',
    category: 'Pilates',
    subcategory: 'Mat',
    equipment_type: 'mat',
    muscles_primary: ['abductors', 'gluteal'],
    muscles_secondary: ['obliques', 'adductor', 'abs'],
    description: 'Side-lying sequence of lifts, kicks and circles targeting the hip abductors and lateral trunk stabilisers.',
    instructions: [
      'Lie on one side with the body in a straight line along the back edge of the mat.',
      'Prop the head on the lower arm and place the top hand in front for support.',
      'Lift the top leg to hip height and hold the pelvis still.',
      'Perform 10 front-and-back kicks, 10 lifts, then 10 small circles each way.',
      'Keep the waist lifted off the mat throughout.',
      'Roll over and repeat on the other side.',
    ],
  },
];

module.exports = { YOGA_PILATES_ENTRIES };
